---
category: Browsing History
date: '2020-12-23'
slug: /browsing-history-2020-12-23
tags: []
title: Oh, The Pages I Goed ~ Dec. 23, 2020
type: post
---


My trip around the web - Dec. 23, 2020

- [Adaptive processes](https://www.notion.so/Adaptive-processes-774e6f7e4202433aa90cbb11cc818e82)
- [Amazon Simple Email Service | Cloud Email Service | Amazon Web Services](https://aws.amazon.com/ses/)
- [Amazon.com : LS LIMO STUDIO LIMOSTUDIO, VAGG1777, Green Chroma Key Background...](https://www.amazon.com/gp/product/B017WNJS3M)
- [Best email newsletter software of 2020 - The Ultimate Guide to Email...](https://zapier.com/learn/email-marketing/best-email-newsletter-software/)
- [Coding Sound With JavaScript: Beginner's Guide | Learning Solutions Magazine](https://learningsolutionsmag.com/articles/coding-sound-with-javascript-beginner-s-guide)
- [Dan Spratling - UX Designer & Frontend Developer](https://danspratling.dev/)
- [Email Marketing With Amazon SES - EasySendy Pro](https://easysendy.com/integrations/amazon-ses/)
- [ES6 Promises in Depth](https://ponyfoo.com/articles/es6-promises-in-depth)
- [GitHub](https://github.com/)
- [Google Search: amazon limit s3 cloudfront](https://www.google.com/search?newwindow=1&client=safari&rls=en&ei=cRXkX7iOGsiB5wL28JGADQ&q=amazon+limit+s3+cloudfront&oq=amazon+limit+s3+cloud)
- [Google Search: amazon ses for newsletters](https://www.google.com/search?client=safari&rls=en&q=amazon+ses+for+newsletters&ie=UTF-8&oe=UTF-8)
- [Google Search: aws email newsletter](https://www.google.com/search?newwindow=1&client=safari&rls=en&ei=VVbiX8XqDsTZ5gLkl4TgDQ&q=aws+email+newsletter&oq=aws+email+newsletter)
- [Google Search: can you stream vods on twitch](https://www.google.com/search?client=safari&rls=en&q=can+you+stream+vods+on+twitch&ie=UTF-8&oe=UTF-8)
- [Google Search: cap s3 cloudfront usate](https://www.google.com/search?client=safari&rls=en&q=cap+s3+cloudfront+usate&ie=UTF-8&oe=UTF-8)
- [Google Search: count letter in string python](https://www.google.com/search?client=safari&rls=en&q=count+letter+in+string+python&ie=UTF-8&oe=UTF-8)
- [Google Search: dom is ready to process](https://www.google.com/search?client=safari&rls=en&q=dom+is+ready+to+process&ie=UTF-8&oe=UTF-8)
- [Google Search: email news letters](https://www.google.com/search?client=safari&rls=en&q=email+news+letters&ie=UTF-8&oe=UTF-8)
- [Google Search: handbrake cli](https://www.google.com/search?client=safari&rls=en&q=handbrake+cli&ie=UTF-8&oe=UTF-8)
- [Google Search: handbrake preset](https://www.google.com/search?client=safari&rls=en&q=handbrake+preset&ie=UTF-8&oe=UTF-8)
- [Google Search: how many seconds in five minutes](https://www.google.com/search?client=safari&rls=en&q=how+many+seconds+in+five+minutes&ie=UTF-8&oe=UTF-8)
- [Google Search: java script while loop](https://www.google.com/search?client=safari&rls=en&q=java+script+while+loop&ie=UTF-8&oe=UTF-8)
- [Google Search: javascript make integer](https://www.google.com/search?client=safari&rls=en&q=javascript+make+integer&ie=UTF-8&oe=UTF-8)
- [Google Search: javascript play sound](https://www.google.com/search?client=safari&rls=en&q=javascript+play+sound&ie=UTF-8&oe=UTF-8)
- [Google Search: javascrtipt](https://www.google.com/search?client=safari&rls=en&q=javascrtipt&ie=UTF-8&oe=UTF-8)
- [Google Search: let var const](https://www.google.com/search?client=safari&rls=en&q=let+var+const&ie=UTF-8&oe=UTF-8)
- [Google Search: mdn js date](https://www.google.com/search?client=safari&rls=en&q=mdn+js+date&ie=UTF-8&oe=UTF-8)
- [Google Search: python file print](https://www.google.com/search?client=safari&rls=en&q=python+file+print&ie=UTF-8&oe=UTF-8)
- [Google Search: python readline](https://www.google.com/search?client=safari&rls=en&q=python+readline&ie=UTF-8&oe=UTF-8)
- [Google Search: python readline remove newline](https://www.google.com/search?client=safari&rls=en&q=python+readline+remove+newline&ie=UTF-8&oe=UTF-8)
- [Google Search: python write file newline](https://www.google.com/search?client=safari&rls=en&q=python+write+file+newline&ie=UTF-8&oe=UTF-8)
- [Google Search: race, gender, religion and age are all examples of](https://www.google.com/search?newwindow=1&client=safari&rls=en&ei=33LjX8urBNKm5gLh5ZRo&q=race%2C+gender%2C+religion+and+age+are+all+examples+of&oq=ages+genders+religions+orientations)
- [Google Search: source unsplash](https://www.google.com/search?client=safari&rls=en&q=source+unsplash&ie=UTF-8&oe=UTF-8)
- [Google Search: twitch rebroadcast](https://www.google.com/search?newwindow=1&client=safari&rls=en&ei=2Z3jX8aGOImm5wKp5pfAAg&q=twitch+rebroadcast&oq=twitch+rebroadcast)
- [Google Search: twitch stream a vod rerun](https://www.google.com/search?newwindow=1&client=safari&rls=en&ei=37jjX46yMoez5gKf-7-QCg&q=twitch+stream+a+vod+rerun&oq=twitch+stream+a+vod+rerun)
- [Google Search: twitch stream a vod rerun](https://www.google.com/search?q=twitch+stream+a+vod+rerun&newwindow=1)
- [Google Search: what does div stand for html](https://www.google.com/search?newwindow=1&client=safari&rls=en&ei=LoLjX4_YFYP45gLR9bCIBA&q=what+does+div+stand+for+html&oq=what+does+div+stand+for+ht)
- [Google Search: youtube audio library](https://www.google.com/search?client=safari&rls=en&q=youtube+audio+library&ie=UTF-8&oe=UTF-8)
- [HandBrake](https://handbrake.fr/rotation.php?file=HandBrake-1.3.3.dmg)
- [HandBrake](https://handbrake.fr/rotation.php?file=HandBrakeCLI-1.3.3.dmg)
- [HandBrake Documentation — CLI Options](https://handbrake.fr/docs/en/latest/cli/cli-options.html)
- [HandBrake Documentation — Command line reference](https://handbrake.fr/docs/en/1.3.0/cli/command-line-reference.html)
- [HandBrake Documentation — Official presets](https://handbrake.fr/docs/en/latest/technical/official-presets.html)
- [HandBrake: Open Source Video Transcoder](https://handbrake.fr/)
- [HTML DOM Audio play() Method](https://www.w3schools.com/jsref/met_audio_play.asp)
- [Mailblast - Email Marketing on a budget using Amazon SES](https://www.mailblast.io/campaigns/5b8602bb-231c-4c22-9de0-01ddcf900c1d/report/overview)
- [MDN: 'audio': The Embed Audio element - HTML: HyperText Markup Language](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio)
- [MDN: Arrow function expressions - JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions)
- [MDN: Audio() - Web APIs](https://developer.mozilla.org/en-US/docs/Web/API/HTMLAudioElement/Audio)
- [MDN: Date - JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date)
- [MDN: Number - JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number)
- [MDN: parseInt() - JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt)
- [MDN: while - JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/while)
- [MJML - The Responsive Email Framework](https://mjml.io/)
- [Open Broadcaster Software®️ | OBS](https://obsproject.com/)
- [Page: DOMContentLoaded, load, beforeunload, unload](https://javascript.info/onload-ondomcontentloaded)
- [Pinboard: bookmarks for alanWsmith](https://pinboard.in/u:alanWsmith)
- [Pinboard: Searching alanWsmith](https://pinboard.in/search/u:alanWsmith?query=ToWatch)
- [Playlist | Fully automated playlist service for 24/7 live streaming! |...](https://easylive.io/en/playlist/)
- [Python 3.9.1 Documentation: 7. Input and Output](https://docs.python.org/3/tutorial/inputoutput.html)
- [Python 3.9.1 Documentation: readline — GNU readline interface](https://docs.python.org/3/library/readline.html)
- [Python String | count() - GeeksforGeeks](https://www.geeksforgeeks.org/python-string-count/)
- [Quotas - Amazon CloudFront](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cloudfront-limits.html#limits-general)
- [Riot reworks Omen's From the Shadows ability in VALORANT | Dot Esports | Dot Esports](https://dotesports.com/valorant/news/riot-reworks-omens-from-the-shadows-ability-in-valorant)
- [Sendy - Send Newsletters 100x cheaper via Amazon SES](https://sendy.co/)
- [Stack Overflow: Getting rid of \n when using .readlines()](https://stackoverflow.com/questions/15233340/getting-rid-of-n-when-using-readlines)
- [Stack Overflow: How to play audio?](https://stackoverflow.com/questions/9419263/how-to-play-audio)
- [Stack Overflow: What is the JavaScript version of sleep()?](https://stackoverflow.com/questions/951021/what-is-the-javascript-version-of-sleep/39914235#39914235)
- [Stack Overflow: Writing string to a file on a new line every time](https://stackoverflow.com/questions/2918362/writing-string-to-a-file-on-a-new-line-every-time)
- [Twitch puts a stop to 24/7 VALORANT rerun streaming | Dot Esports](https://dotesports.com/news/twitch-puts-a-stop-to-24-7-valorant-rerun-streaming)
- [Twitch.tv - Community Guidelines](https://www.twitch.tv/p/legal/community-guidelines/)
- [Twitter: :party-corgi: - if I'm reading this right, I wrote over 170 posts...](https://twitter.com/chrisbiscardi/status/1341886943647256576)
- [Twitter: @dan_spratling (Dan Spratling 🚀)](https://twitter.com/dan_spratling)
- [Twitter: fireside chaos 🍜 - NON-CHRISTIANS: respond with ONE word. what do...](https://twitter.com/emmatsalageek/status/1341550089093996546)
- [Twitter: Kerri Miller (Allegedly) - In retrospect, we all should've waited...](https://twitter.com/kerrizor/status/1341759513590812672)
- [Twitter: Yuliana - I’m thrilled to announce that 2 weeks ago I accepted a job...](https://twitter.com/yulianahazda/status/1341571647229349893)
- [Unsplash Source | A Simple API for Embedding Free Photos from Unsplash](https://source.unsplash.com/)
- [Use CloudFront to serve HTTPS requests for your Amazon S3 bucket](https://aws.amazon.com/premiumsupport/knowledge-center/cloudfront-https-requests-s3/)
- [Var, Let, and Const – What's the Difference?](https://www.freecodecamp.org/news/var-let-and-const-whats-the-difference/)
- [Video On Demand](https://help.twitch.tv/s/article/video-on-demand?language=en_US)
- [Wikipedia: Wikipedia:Categorization/Ethnicity, gender, religion and sexuality](https://en.wikipedia.org/wiki/Wikipedia:Categorization/Ethnicity,_gender,_religion_and_sexuality)
- [Writing to a File with Python's print() Function](https://stackabuse.com/writing-to-a-file-with-pythons-print-function/)
- [YouTube: How to Create an Authenticated REST API on AWS with API Gateway,...](https://www.youtube.com/watch?v=fs9HfYbWjXQ)
- [YouTube: Real Workplace Stoicism - Virtues, Duties, Fitting In, & Fixing...](https://www.youtube.com/watch?v=Q0uUvG-5iDw&feature=youtu.be)
- [YouTube: YouTube Audio Library Download](https://www.youtube.com/c/YouTubeAudioLibraryDownload/videos)