---
category: Browsing History
date: '2020-10-20'
slug: /browsing-history-2020-10-20
tags: []
title: Oh, The Places I Went! ~ Oct. 20, 2020
type: post
---


- [1x Engineer](https://1x.engineer/)
- [Amazon Cognito - Simple and Secure User Sign Up & Sign In | Amazon Web Services (AWS)](https://aws.amazon.com/cognito/)
- [Apple Mac Upgrades - RAM, SSD Flash, External Drives and More](https://eshop.macsales.com/)
- [Apple Support: Add JavaScript scripts to a workflow in Automator on Mac](https://support.apple.com/guide/automator/add-javascript-scripts-to-a-workflow-auta229c77c2/mac)
- [Apple Support: Automate Script Editor tasks in Script Editor on Mac](https://support.apple.com/en-au/guide/script-editor/scpedt1125/mac)
- [AppleScript Finder window count in Mojave - macOS / AppleScript - Automators Talk](https://talk.automators.fm/t/applescript-finder-window-count-in-mojave/3383)
- [Array - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array)
- [Blog Posts – Tabletop Dropouts Official Website](https://ttdpodcast.com/index.php/category/blog-posts/)
- [Case insensitive search in man pages - Unix & Linux Stack Exchange](https://unix.stackexchange.com/questions/101295/case-insensitive-search-in-man-pages)
- [Case insensitive search in man pages - Unix & Linux Stack Exchange](https://unix.stackexchange.com/questions/101295/case-insensitive-search-in-man-pages/101427#101427)
- [Command line access to the Mac keychain | Die wunderbare Welt von Isotopp](https://blog.koehntopp.info/2017/01/26/command-line-access-to-the-mac-keychain.html)
- [Example Domain](https://www.example.com/)
- [Fix MacBook Pro Random Shutdown - One Click Solution](https://realmacmods.com/product/macbook-pro-nocrash-utility/)
- [Google Search: applescript array](https://www.google.com/search?client=safari&rls=en&q=applescript+array&ie=UTF-8&oe=UTF-8)
- [Google Search: applescript do javascript](https://www.google.com/search?client=safari&rls=en&q=applescript+do+javascript&ie=UTF-8&oe=UTF-8)
- [Google Search: applescript hash](https://www.google.com/search?client=safari&rls=en&q=applescript+hash&ie=UTF-8&oe=UTF-8)
- [Google Search: applscript javascrtipt log print](https://www.google.com/search?client=safari&rls=en&q=applscript+javascrtipt+log+print&ie=UTF-8&oe=UTF-8)
- [Google Search: big sur mac os version](https://www.google.com/search?client=safari&rls=en&q=big+sur+mac+os+version&ie=UTF-8&oe=UTF-8)
- [Google Search: cognito](https://www.google.com/search?newwindow=1&client=safari&rls=en&ei=DKGPX_LEJqWD5wK-kKjABQ&q=cognito&oq=cognito&gs_lcp=CgZwc3ktYWIQAzIECAAQRzIECAAQRzIECAAQRzIECAAQR1DnI1jnI2CaJWgAcAN4AIABAIgBAJIBAJgBAKABAaoBB2d3cy13aXrIAQTAAQE&sclient=psy-ab&ved=0ahUKEwjy-qvZ1cTsAhWlwVkKHT4IClgQ4dUDCAw&uact=5)
- [Google Search: getelementbytype](https://www.google.com/search?client=safari&rls=en&q=getelementbytype&ie=UTF-8&oe=UTF-8)
- [Google Search: javascript array](https://www.google.com/search?client=safari&rls=en&q=javascript+array&ie=UTF-8&oe=UTF-8)
- [Google Search: javascript automation apple count window](https://www.google.com/search?client=safari&rls=en&q=javascript+automation+apple+count+window&ie=UTF-8&oe=UTF-8)
- [Google Search: javascript for loop](https://www.google.com/search?client=safari&rls=en&q=javascript+for+loop&ie=UTF-8&oe=UTF-8)
- [Google Search: javascript mac count window](https://www.google.com/search?client=safari&rls=en&q=javascript+mac+count+window&ie=UTF-8&oe=UTF-8)
- [Google Search: javascript osa open application](https://www.google.com/search?client=safari&rls=en&q=javascript+osa+open+application&ie=UTF-8&oe=UTF-8)
- [Google Search: keychain access](https://www.google.com/search?client=safari&rls=en&q=keychain+access&ie=UTF-8&oe=UTF-8)
- [Google Search: mac sales](https://www.google.com/search?client=safari&rls=en&q=mac+sales&ie=UTF-8&oe=UTF-8)
- [Google Search: man page case insensitive search](https://www.google.com/search?client=safari&rls=en&q=man+page+case+insensitive+search&ie=UTF-8&oe=UTF-8)
- [Google Search: nocrash macbook](https://www.google.com/search?newwindow=1&client=safari&rls=en&biw=937&bih=587&ei=FZ2PX7yrOMaE5wLlnqfYDA&q=nocrash+macbook&oq=nocrash+macbook&gs_lcp=CgZwc3ktYWIQAzIICAAQCBAKEB5QuE1YuE1go1JoAHAAeACAAW-IAaQCkgEDMi4xmAEAoAEBqgEHZ3dzLXdpesABAQ&sclient=psy-ab&ved=0ahUKEwj8ib_10cTsAhVGwlkKHWXPCcsQ4dUDCAw&uact=5)
- [Google Search: nocrashmacbook](https://www.google.com/search?newwindow=1&client=safari&rls=en&biw=937&bih=587&ei=EJ2PX5qaKcKb5gLBuriwBg&q=nocrashmacbook&oq=nocrashmacbook&gs_lcp=CgZwc3ktYWIQAzoECAAQRzoFCAAQkQI6AggAOgUIABCxAzoICC4QsQMQgwE6CAgAELEDEIMBOgsILhCxAxDHARCjAjoECAAQQzoECC4QQzoHCAAQyQMQQzoCCC46BwgAELEDEEM6BwguELEDEEM6BwgAEMkDEAo6BQgAEMkDOggILhDHARCvAToECAAQCjoKCC4QxwEQrwEQCjoECAAQHjoGCAAQChAeOgYIABAFEB5QoghYrh9ggyJoAHACeACAAWmIAdsJkgEDOS41mAEAoAEBqgEHZ3dzLXdpesgBCMABAQ&sclient=psy-ab&ved=0ahUKEwia4v7y0cTsAhXCjVkKHUEdDmYQ4dUDCAw&uact=5)
- [Google Search: node js](https://www.google.com/search?client=safari&rls=en&q=node+js&ie=UTF-8&oe=UTF-8)
- [Google Search: parameter store aws](https://www.google.com/search?client=safari&rls=en&q=parameter+store+aws&ie=UTF-8&oe=UTF-8)
- [Google Search: python get current username mac](https://www.google.com/search?client=safari&rls=en&q=python+get+current+username+mac&ie=UTF-8&oe=UTF-8)
- [Google Search: python run external command](https://www.google.com/search?client=safari&rls=en&q=python+run+external+command&ie=UTF-8&oe=UTF-8)
- [Google Search: when did node come out](https://www.google.com/search?client=safari&rls=en&q=when+did+node+come+out&ie=UTF-8&oe=UTF-8)
- [Google Search: work secrets manager](https://www.google.com/search?client=safari&rls=en&q=work+secrets+manager&ie=UTF-8&oe=UTF-8)
- [How to get the current username in Python](https://www.kite.com/python/answers/how-to-get-the-current-username-in-python)
- [Issues · nodejs/help](https://github.com/nodejs/help/issues)
- [keyring · PyPI](https://pypi.org/project/keyring/)
- [Kristian Köhntopp (@isotopp) / Twitter](https://twitter.com/isotopp)
- [Loops and iteration - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Loops_and_iteration)
- [Mac Automation Scripting Guide: Displaying Progress](https://developer.apple.com/library/archive/documentation/LanguagesUtilities/Conceptual/MacAutomationScriptingGuide/DisplayProgress.html)
- [Mac Automation Scripting Guide: Manipulating Lists of Items](https://developer.apple.com/library/archive/documentation/LanguagesUtilities/Conceptual/MacAutomationScriptingGuide/ManipulateListsofItems.html)
- [macos-keychain · PyPI](https://pypi.org/project/macos-keychain/)
- [MacScripter / Hash table: A good alternative for records](https://www.macscripter.net/viewtopic.php?id=39424)
- [Node.js at PayPal | by PayPal Engineering | PayPal Engineering | Medium](https://medium.com/paypal-engineering/node-js-at-paypal-4e2d1d08ce4f)
- [Python methods to interact with Mac OS X Keychain](https://gist.github.com/gcollazo/9434580)
- [Setting Window Sizes Precisely With a Script](https://macmost.com/setting-window-sizes-precisely-with-a-script.html)
- [Stack Overflow: How do I create a list of records in applescript](https://stackoverflow.com/questions/18815921/how-do-i-create-a-list-of-records-in-applescript/18816682)
- [Stack Overflow: How do you start an application in Javascript via osascript?](https://stackoverflow.com/questions/29408703/how-do-you-start-an-application-in-javascript-via-osascript)
- [Stack Overflow: How to call an external command?](https://stackoverflow.com/questions/89228/how-to-call-an-external-command)
- [Stack Overflow: How to fetch proxy password from osx keychain in python?](https://stackoverflow.com/questions/29740808/how-to-fetch-proxy-password-from-osx-keychain-in-python)
- [Stack Overflow: Is there a portable way to get the current username in Python?](https://stackoverflow.com/questions/842059/is-there-a-portable-way-to-get-the-current-username-in-python)
- [Stack Overflow: osx yosemite - How to log to message window in Script Editor using JavaScript for Automation](https://stackoverflow.com/questions/27609455/how-to-log-to-message-window-in-script-editor-using-javascript-for-automation/27609609#27609609)
- [Stack Overflow: why doesn't 'do javascript' call in Applescript execute when the same code typed into browser does?](https://stackoverflow.com/questions/6561452/why-doesnt-do-javascript-call-in-applescript-execute-when-the-same-code-typed/6563447#6563447)
- [Using the OS X Keychain to store and retrieve passwords](https://www.netmeister.org/blog/keychain-passwords.html)
- [What Is AWS Secrets Manager? - AWS Secrets Manager](https://docs.aws.amazon.com/secretsmanager/latest/userguide/intro.html)
- [Wikipedia: macOS Big Sur](https://en.wikipedia.org/wiki/MacOS_Big_Sur)
- [YouTube: Two Gunslingers - Tom Petty](https://www.youtube.com/watch?v=wFS9wZQ9NiY)